### ISSUE TITLE
Could you publish a new version of this package?

### ISSUE THREAD

**Issue by Jackenmen** [carsonoid/sublime_man_page_support#7]
This package is currently failing due to an ImportError that appears to have already been fixed in #4 but currently, no version with that fix has been published to Package Control.
```
Traceback (most recent call last):
  File "/opt/sublime_text/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/Lib/python33/sublime_plugin.py", line 1692, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/home/ubuntu/.config/sublime-text/Installed Packages/Man Page Support.sublime-package/new_page.py", line 5, in <module>
ImportError: No module named 'sublime_lib.path'
```

**Comment by Landohlakes** [comment]
ok
